name: Deploy Worker
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: worker  # your worker folder path

    steps:
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
